Repository JDFED/drip-form, pull requests merged in 2021-12, with the labels that each got.

#44 fix: monaco-editor always in loading
  packages/generator/src/components/RightSideBar/MonacoEdit/index.tsx
Labels: bug

#62 底部取消按钮添加onCancel回调
  packages/drip-form/src/DripForm/Footer/index.tsx
  packages/drip-form/src/DripForm/index.tsx
  packages/drip-form/src/DripForm/type.ts
Labels: enhancement, awaiting-approval

#64 feat: generator数组容器支持配置新增按钮文案
  packages/generator/src/fields/container/array.field.ts
Labels: awaiting-approval

#67 fix: 修改组件初始默认值设置
  packages/drip-form/src/render/index.tsx
Labels: bug

#77 fix: editConfig parse 函数 showTitle 判空逻辑错误修复
  packages/generator/src/components/RightSideBar/PropertyConfig/index.tsx
Labels: bug

#76 feat: module bar styles support custom
  packages/generator/src/components/LeftSideBar/DragAtom/Item/index.module.css
  packages/generator/src/components/LeftSideBar/DragAtom/Item/index.tsx
  packages/generator/src/components/LeftSideBar/DragAtom/index.tsx
  packages/generator/src/components/LeftSideBar/index.tsx
  packages/generator/src/fields/types.ts
Labels: enhancement
